version: "3.8"

services:
  portfolio_node:
    container_name: portfolio_node
    build:
      context: .
      dockerfile: dockerfile.node
    ports:
      - "4000:4000"
    env_file:
      - back.env
    entrypoint: npm start
    depends_on:
      - db

  db:
    container_name: portfolio_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    env_file:
      - back.env

    volumes:
      - portfolio_data:/var/lib/postgresql/data

volumes:
  portfolio_data: {}
